/* automatically generated by configure */
/* edit configure.in to change version number */
#define PHP_MAJOR_VERSION 5
#define PHP_MINOR_VERSION 4
#define PHP_RELEASE_VERSION 46
#define PHP_EXTRA_VERSION ".4T"
#define PHP_VERSION "5.4.46.4T"
#define PHP_VERSION_ID 50446
